@startuml
'https://plantuml.com/sequence-diagram


actor       Пользователь                        as user
boundary    "AuthorListView"                   as ts
control     "AuthorListController"        as tsc
control     "ListStateNotifier"        as lsn
entity      "AuthorDBDataSource"           as srep

user -> ts : Клик на <<Удалить>>
ts -> tsc : delete_selected
tsc -> srep : remove
srep --> tsc
tsc --> ts
ts -> tsc : refresh_data
tsc -> srep : get_list
srep --> tsc
tsc -> lsn : delete
lsn -> ts : update
ts --> lsn
lsn --> tsc
ts --> tsc
tsc --> ts
ts --> user

@enduml


